gke-standard-nginx/readme-update
GoogleCloudPlatform/click-to-deploy-solutions pull request #41
Opened 2023-06-14 17:29 UTC by gruizmm

Updating different sections of the readme file.

2023-06-20 14:41 UTC, fellipeamedeiros commented on gke-standard-nginx/README.md
> -![architecture](architecture.png)
@gruizmm can we put the Architecture again?

2023-06-22 12:42 UTC, sylvioneto requested changes

2023-06-30 17:10 UTC, sylvioneto commented on gke-standard-nginx/README.md
> +# Automate the deployment of your Kubernetes applications
Great title, Gabriel! thank you

2023-06-30 17:11 UTC, sylvioneto approved these changes
lgtm

2023-06-30 17:11 UTC, merged